// Gostafa 2026.
// SPDX-License-Identifier: Apache-2.0.

package goloader

import (
	"context"
	"errors"
	"fmt"
	"go/ast"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/gostafa/distance/internal/features/typefacts/domain/model"
	"github.com/gostafa/distance/internal/features/typefacts/ports/outbound"
	"golang.org/x/tools/go/packages"
)

func writeModule(t *testing.T, files map[string]string) string {
	t.Helper()

	dir := t.TempDir()

	err := os.WriteFile(
		filepath.Join(dir, "go.mod"),
		[]byte("module example.com/cov\n\ngo 1.22\n"),
		0o600,
	)
	if err != nil {
		t.Fatal(err)
	}

	for name, content := range files {
		path := filepath.Join(dir, name)

		err := os.MkdirAll(filepath.Dir(path), 0o755)
		if err != nil {
			t.Fatal(err)
		}

		err = os.WriteFile(path, []byte(content), 0o600)
		if err != nil {
			t.Fatal(err)
		}
	}

	return dir
}

func TestExtractRichTypeShapes(t *testing.T) {
	dir := writeModule(t, map[string]string{
		"shapes/shapes.go": `
package shapes

type Other struct{}

type Closer interface{ Close() }

type Holder struct {
	Ptr   *Other
	List  []Other
	Dict  map[Other]Other
	Fn    func(Other) Other
	Anon  struct{ Nested *Other }
	Iface interface {
		Closer
		Do(Other) Other
	}
}

func Helper() {}

type Alias = Other

const Const = 1

var _ = Const

func (h *Holder) Use() {}
`,
		"shapes/gen.go": `// Code generated by tool. DO NOT EDIT.

package shapes

type Generated struct{ X int }

func (g *Generated) Run() {}
`,
		"iface/iface.go": `
package iface

type Speaker interface {
	Speak()
}

type Talker int

func (Talker) Speak() {}
`,
	})

	out := load(t.Context(), defaultLoaderRuntime(), &outbound.FactOptions{
		Directory:        dir,
		Patterns:         nil, // exercises ./... default
		IncludeGenerated: true,
		BuildTags:        []string{"ignoretag"},
	})
	if out.err != nil {
		t.Fatal(out.err)
	}

	if out.mod != "example.com/cov" {
		t.Fatalf("module = %q", out.mod)
	}

	foundGen := false
	foundHolder := false

	for _, pkg := range out.ext {
		if !strings.HasSuffix(pkg.Path, "/shapes") {
			continue
		}

		for _, te := range pkg.Types {
			switch te.Name {
			case "Generated":
				foundGen = true
			case "Holder":
				foundHolder = true
			}
		}
	}

	if !foundHolder {
		t.Fatal("Holder not extracted")
	}

	if !foundGen {
		t.Fatal("Generated type missing with IncludeGenerated=true")
	}

	out2 := load(t.Context(), defaultLoaderRuntime(), &outbound.FactOptions{
		Directory: dir,
		Patterns:  []string{"./shapes"},
	})
	if out2.err != nil {
		t.Fatal(out2.err)
	}

	for _, pkg := range out2.ext {
		for _, te := range pkg.Types {
			if te.Name == "Generated" {
				t.Fatal("Generated should be skipped when IncludeGenerated=false")
			}
		}
	}

	foundTalker := false

	for _, pkg := range out.ext {
		if !strings.HasSuffix(pkg.Path, "/iface") {
			continue
		}

		for _, te := range pkg.Types {
			if te.Name == "Talker" {
				foundTalker = true

				if te.Kind != model.KindOther {
					t.Fatalf("Talker kind = %d, want other", te.Kind)
				}
			}
		}
	}

	if !foundTalker {
		t.Fatal("Talker not extracted")
	}
}

func TestSkipPos(t *testing.T) {
	fset := token.NewFileSet()
	f := fset.AddFile("gen.go", -1, 20)
	f.SetLinesForContent([]byte("package x\n"))

	filter := skipFilter{
		fset:      fset,
		generated: map[string]bool{f.Name(): true},
		opts:      &extractorOptions{includeGenerated: true},
	}

	if skipPos(&filter, token.Pos(f.Base())) {
		t.Fatal("includeGenerated=true must not skip")
	}

	filter.opts.includeGenerated = false

	if !skipPos(&filter, token.Pos(f.Base())) {
		t.Fatal("generated file should be skipped")
	}
}

func TestSelectPackagesTruncation(t *testing.T) {
	loaded := make([]*packages.Package, 0, 12)

	for i := range 12 {
		loaded = append(loaded, &packages.Package{
			PkgPath: fmt.Sprintf("m/p%d", i),
			Errors:  []packages.Error{{Msg: "boom"}},
		})
	}

	_, err := selectPackages(loaded, &outbound.FactOptions{})

	if err == nil || !strings.Contains(err.Error(), "and 2 more") {
		t.Fatalf("truncation error = %v", err)
	}
}

func TestLoadPackagesSeamErrors(t *testing.T) {
	sentinel := errors.New("load boom")
	runtime := defaultLoaderRuntime()

	runtime.packagesLoad = func(*packages.Config, ...string) ([]*packages.Package, error) {
		return nil, sentinel
	}

	if _, err := loadPackages(
		t.Context(),
		runtime,
		&outbound.FactOptions{Patterns: []string{"./"}},
	); !errors.Is(
		err,
		sentinel,
	) {

		t.Fatalf("load error = %v", err)
	}

	runtime.packagesLoad = func(*packages.Config, ...string) ([]*packages.Package, error) {
		return nil, nil
	}

	if _, err := loadPackages(
		t.Context(),
		runtime,
		&outbound.FactOptions{Patterns: []string{"./x"}},
	); err == nil ||
		!strings.Contains(err.Error(), "no packages matched") {

		t.Fatalf("empty load = %v", err)
	}

	runtime.packagesLoad = func(*packages.Config, ...string) ([]*packages.Package, error) {
		return []*packages.Package{{
			PkgPath: "m/broken",
			Errors:  []packages.Error{{Msg: "x"}},
		}}, nil
	}

	if _, err := loadPackages(t.Context(), runtime, &outbound.FactOptions{
		Patterns: []string{"./x"}, ContinueOnError: true,
	}); err == nil || !strings.Contains(err.Error(), "no loadable packages") {
		t.Fatalf("no loadable = %v", err)
	}
}

func TestExtractAllWorkerError(t *testing.T) {
	sentinel := errors.New("extract failed")
	runtime := defaultLoaderRuntime()

	runtime.runExtractWorkers = func(context.Context, WorkerRun, func(int) error) error {
		return sentinel
	}

	pkg := healthy("m/a", "a.go")
	_, err := extractAll(
		t.Context(),
		runtime,
		&extractJob{
			pkgs:       []*packages.Package{pkg},
			opts:       &outbound.FactOptions{},
			modulePath: "m",
		},
	)

	if !errors.Is(err, sentinel) {
		t.Fatalf("extractAll = %v", err)
	}

	runtime.packagesLoad = func(*packages.Config, ...string) ([]*packages.Package, error) {
		return []*packages.Package{healthy("m/a", "a.go")}, nil
	}
	loaded := load(t.Context(), runtime, &outbound.FactOptions{Patterns: []string{"./a"}})

	if !errors.Is(loaded.err, sentinel) {
		t.Fatalf("load extract error = %v", loaded.err)
	}
}

func TestTypeKindClassification(t *testing.T) {
	dir := writeModule(t, map[string]string{
		"k.go": `
package k
type S struct{}
type I interface{ M() }
type A int
`,
	})

	out := load(t.Context(), defaultLoaderRuntime(), &outbound.FactOptions{
		Directory: dir,
		Patterns:  []string{"."},
	})
	if out.err != nil {
		t.Fatal(out.err)
	}

	kinds := map[string]uint8{}

	for _, te := range out.ext[0].Types {
		kinds[te.Name] = te.Kind
	}

	if kinds["S"] != model.KindStruct || kinds["I"] != model.KindInterface ||
		kinds["A"] != model.KindOther {

		t.Fatalf("kinds = %+v", kinds)
	}
}

func TestExtractPackageSkipsNonNamedTypeName(t *testing.T) {
	fset := token.NewFileSet()
	file := fset.AddFile("b.go", -1, 20)
	file.SetLinesForContent([]byte("package m\n"))

	tpkg := types.NewPackage("m", "m")
	// TypeParam: IsAlias=false but Type() is not *Named.
	tn := types.NewTypeName(token.Pos(file.Base()), tpkg, "T", nil)

	_ = types.NewTypeParam(tn, types.NewInterfaceType(nil, nil))
	tpkg.Scope().Insert(tn)

	pkg := &packages.Package{
		PkgPath:   "m",
		Fset:      fset,
		Types:     tpkg,
		TypesInfo: &types.Info{},
		Syntax:    []*ast.File{{Name: &ast.Ident{Name: "m"}}},
	}
	out := extractPackage(pkg, &extractorOptions{})

	if len(out.Types) != 0 {
		t.Fatalf("types = %+v, want none", out.Types)
	}
}
