package goloader

import (
	"context"
	"errors"
	"fmt"
	"go/ast"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/gostafa/distance/internal/features/typefacts/domain"
	"github.com/gostafa/distance/internal/features/typefacts/ports/outbound"
	"golang.org/x/tools/go/packages"
)

func writeModule(t *testing.T, files map[string]string) string {
	t.Helper()

	dir := t.TempDir()
	if err := os.WriteFile(
		filepath.Join(dir, "go.mod"),
		[]byte("module example.com/cov\n\ngo 1.22\n"),
		0o600,
	); err != nil {
		t.Fatal(err)
	}
	for name, content := range files {
		path := filepath.Join(dir, name)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
			t.Fatal(err)
		}
	}

	return dir
}

func TestExtractRichTypeShapes(t *testing.T) {
	dir := writeModule(t, map[string]string{
		"shapes/shapes.go": `
package shapes

type Other struct{}

type Closer interface{ Close() }

type Holder struct {
	Ptr   *Other
	List  []Other
	Dict  map[Other]Other
	Fn    func(Other) Other
	Anon  struct{ Nested *Other }
	Iface interface {
		Closer
		Do(Other) Other
	}
}

func Helper() {}

type Alias = Other

const Const = 1

var _ = Const

func (h *Holder) Use() {}
`,
		"shapes/gen.go": `// Code generated by tool. DO NOT EDIT.

package shapes

type Generated struct{ X int }

func (g *Generated) Run() {}
`,
		"iface/iface.go": `
package iface

type Speaker interface {
	Speak()
}

type Talker int

func (Talker) Speak() {}
`,
	})

	mod, pkgs, err := load(context.Background(), outbound.FactOptions{
		Directory:        dir,
		Patterns:         nil, // exercises ./... default
		IncludeGenerated: true,
		BuildTags:        []string{"ignoretag"},
	})
	if err != nil {
		t.Fatal(err)
	}
	if mod != "example.com/cov" {
		t.Fatalf("module = %q", mod)
	}

	foundGen := false
	foundHolder := false
	for _, pkg := range pkgs {
		if !strings.HasSuffix(pkg.Path, "/shapes") {
			continue
		}
		for _, te := range pkg.Types {
			switch te.Name {
			case "Generated":
				foundGen = true
			case "Holder":
				foundHolder = true
			}
		}
	}
	if !foundHolder {
		t.Fatal("Holder not extracted")
	}
	if !foundGen {
		t.Fatal("Generated type missing with IncludeGenerated=true")
	}

	_, pkgs2, err := load(context.Background(), outbound.FactOptions{
		Directory: dir,
		Patterns:  []string{"./shapes"},
	})
	if err != nil {
		t.Fatal(err)
	}
	for _, pkg := range pkgs2 {
		for _, te := range pkg.Types {
			if te.Name == "Generated" {
				t.Fatal("Generated should be skipped when IncludeGenerated=false")
			}
		}
	}

	foundTalker := false
	for _, pkg := range pkgs {
		if !strings.HasSuffix(pkg.Path, "/iface") {
			continue
		}
		for _, te := range pkg.Types {
			if te.Name == "Talker" {
				foundTalker = true
				if te.Kind != domain.KindOther {
					t.Fatalf("Talker kind = %d, want other", te.Kind)
				}
			}
		}
	}
	if !foundTalker {
		t.Fatal("Talker not extracted")
	}
}

func TestSkipPos(t *testing.T) {
	fset := token.NewFileSet()
	f := fset.AddFile("gen.go", -1, 20)
	f.SetLinesForContent([]byte("package x\n"))
	if skipPos(fset, true, map[string]bool{f.Name(): true}, token.Pos(f.Base())) {
		t.Fatal("includeGenerated=true must not skip")
	}
	if !skipPos(fset, false, map[string]bool{f.Name(): true}, token.Pos(f.Base())) {
		t.Fatal("generated file should be skipped")
	}
}

func TestSelectPackagesTruncation(t *testing.T) {
	loaded := make([]*packages.Package, 0, 12)
	for i := 0; i < 12; i++ {
		loaded = append(loaded, &packages.Package{
			PkgPath: fmt.Sprintf("m/p%d", i),
			Errors:  []packages.Error{{Msg: "boom"}},
		})
	}
	_, err := selectPackages(loaded, false)
	if err == nil || !strings.Contains(err.Error(), "and 2 more") {
		t.Fatalf("truncation error = %v", err)
	}
}

func TestLoadPackagesSeamErrors(t *testing.T) {
	orig := packagesLoad
	t.Cleanup(func() { packagesLoad = orig })

	sentinel := errors.New("load boom")
	packagesLoad = func(*packages.Config, ...string) ([]*packages.Package, error) {
		return nil, sentinel
	}
	if _, err := loadPackages(
		context.Background(),
		outbound.FactOptions{Patterns: []string{"./"}},
	); !errors.Is(
		err,
		sentinel,
	) {
		t.Fatalf("load error = %v", err)
	}

	packagesLoad = func(*packages.Config, ...string) ([]*packages.Package, error) {
		return nil, nil
	}
	if _, err := loadPackages(
		context.Background(),
		outbound.FactOptions{Patterns: []string{"./x"}},
	); err == nil ||
		!strings.Contains(err.Error(), "no packages matched") {
		t.Fatalf("empty load = %v", err)
	}

	packagesLoad = func(*packages.Config, ...string) ([]*packages.Package, error) {
		return []*packages.Package{{
			PkgPath: "m/broken",
			Errors:  []packages.Error{{Msg: "x"}},
		}}, nil
	}
	if _, err := loadPackages(context.Background(), outbound.FactOptions{
		Patterns: []string{"./x"}, ContinueOnError: true,
	}); err == nil || !strings.Contains(err.Error(), "no loadable packages") {
		t.Fatalf("no loadable = %v", err)
	}
}

func TestExtractAllWorkerError(t *testing.T) {
	orig := runExtractWorkers
	t.Cleanup(func() { runExtractWorkers = orig })

	sentinel := errors.New("extract failed")
	runExtractWorkers = func(context.Context, int, int, func(int) error) error {
		return sentinel
	}

	pkg := healthy("m/a", "a.go")
	_, err := extractAll(
		context.Background(),
		[]*packages.Package{pkg},
		outbound.FactOptions{},
		"m",
	)
	if !errors.Is(err, sentinel) {
		t.Fatalf("extractAll = %v", err)
	}

	packagesLoadOrig := packagesLoad
	t.Cleanup(func() { packagesLoad = packagesLoadOrig })
	packagesLoad = func(*packages.Config, ...string) ([]*packages.Package, error) {
		return []*packages.Package{healthy("m/a", "a.go")}, nil
	}
	_, _, err = load(context.Background(), outbound.FactOptions{Patterns: []string{"./a"}})
	if !errors.Is(err, sentinel) {
		t.Fatalf("load extract error = %v", err)
	}
}

func TestTypeKindClassification(t *testing.T) {
	dir := writeModule(t, map[string]string{
		"k.go": `
package k
type S struct{}
type I interface{ M() }
type A int
`,
	})
	_, pkgs, err := load(context.Background(), outbound.FactOptions{
		Directory: dir,
		Patterns:  []string{"."},
	})
	if err != nil {
		t.Fatal(err)
	}
	kinds := map[string]domain.TypeKind{}
	for _, te := range pkgs[0].Types {
		kinds[te.Name] = te.Kind
	}
	if kinds["S"] != domain.KindStruct || kinds["I"] != domain.KindInterface || kinds["A"] != domain.KindOther {
		t.Fatalf("kinds = %+v", kinds)
	}
}

func TestExtractPackageSkipsNonNamedTypeName(t *testing.T) {
	fset := token.NewFileSet()
	file := fset.AddFile("b.go", -1, 20)
	file.SetLinesForContent([]byte("package m\n"))

	tpkg := types.NewPackage("m", "m")
	// TypeParam: IsAlias=false but Type() is not *Named.
	tn := types.NewTypeName(token.Pos(file.Base()), tpkg, "T", nil)
	_ = types.NewTypeParam(tn, types.NewInterfaceType(nil, nil))
	tpkg.Scope().Insert(tn)

	pkg := &packages.Package{
		PkgPath:   "m",
		Fset:      fset,
		Types:     tpkg,
		TypesInfo: &types.Info{},
		Syntax:    []*ast.File{{Name: &ast.Ident{Name: "m"}}},
	}
	out := extractPackage(pkg, extractorOptions{})
	if len(out.Types) != 0 {
		t.Fatalf("types = %+v, want none", out.Types)
	}
}
